
import { Product } from './types';

export const TV_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Smart TV DLED 32 HD Multi Android 11 3HDMI 2USB Bluetooth - TL062M",
    price: 1029.00,
    oldPrice: 1299.00,
    discount: 21,
    sales: 1500,
    rating: 4.8,
    screenSize: '32',
    os: 'Android TV',
    imageUrl: "https://i.postimg.cc/yxtTj2Rg/image.png",
    affiliateUrl: "https://s.shopee.com.br/qcrBGLSDx",
  },
  {
    id: 2,
    name: "Smart TV HQ 32\" HD tela sem Bordas Sistema Android Design Slim HQS32NKHM",
    price: 819.00,
    oldPrice: 1399.00,
    discount: 41,
    sales: 850,
    rating: 4.7,
    screenSize: '32',
    os: 'Android TV',
    imageUrl: "https://i.postimg.cc/vBypZcHg/image.png",
    affiliateUrl: "https://s.shopee.com.br/1gByBsZ96I",
  },
  {
    id: 3,
    name: "SMART TV 32\" TRONOS PRETO TRS32SFA11 HD",
    price: 799.90,
    oldPrice: 1199.00,
    discount: 33,
    sales: 450,
    rating: 4.5,
    screenSize: '32',
    os: 'Android TV',
    imageUrl: "https://i.postimg.cc/mkydpwQC/image.png",
    affiliateUrl: "https://s.shopee.com.br/2Vl5BlwLwt",
  },
  {
    id: 4,
    name: "Smart TV DLED 55 4K DLED Toshiba 55C350NS VIDAA 3 HDMI 2 USB Wi-Fi - TB030M",
    price: 2609.00,
    oldPrice: 3299.00,
    discount: 21,
    sales: 320,
    rating: 4.9,
    screenSize: '55+',
    os: 'VIDAA',
    imageUrl: "https://i.postimg.cc/qR3BKt2b/image.png",
    affiliateUrl: "https://s.shopee.com.br/1BFhbZCtrJ",
  },
  {
    id: 5,
    name: "Smart TV AOC 32 Polegadas Roku 32S5045/78G HD Wi-Fi HDMI USB",
    price: 927.99,
    oldPrice: 1349.00,
    discount: 31,
    sales: 1200,
    rating: 4.8,
    screenSize: '32',
    os: 'Roku TV',
    imageUrl: "https://i.postimg.cc/BQ8pK4zZ/image.png",
    affiliateUrl: "https://s.shopee.com.br/8Kis8vpZKh",
  },
  {
    id: 6,
    name: "Smart TV 32 polegadas LED HD Wi-Fi TV 60Hz 32wdsnbx 100/240v Android 14",
    price: 795.98,
    oldPrice: 1099.00,
    discount: 27,
    sales: 620,
    rating: 4.6,
    screenSize: '32',
    os: 'Android TV',
    imageUrl: "https://i.postimg.cc/XJdGb11j/image.png",
    affiliateUrl: "https://s.shopee.com.br/4LCjNpKny5",
  },
  {
    id: 7,
    name: "Smart TV LED AOC 40 Polegadas Full HD Roku 40S5045/78 Wi-Fi HDMI Preta",
    price: 1109.00,
    oldPrice: 1699.00,
    discount: 34,
    sales: 980,
    rating: 4.7,
    screenSize: '40',
    os: 'Roku TV',
    imageUrl: "https://i.postimg.cc/kX3rG11g/image.png",
    affiliateUrl: "https://s.shopee.com.br/7AWulIL9db",
  },
  {
    id: 8,
    name: "Smart TV HQ 50\" UHD tela sem bordas Sistema Android Design Slim HQS50NKHM",
    price: 1599.00,
    oldPrice: 1999.00,
    discount: 20,
    sales: 240,
    rating: 4.6,
    screenSize: '50',
    os: 'Android TV',
    imageUrl: "https://i.postimg.cc/dQXsBjWF/image.png",
    affiliateUrl: "https://s.shopee.com.br/13kERVURh",
  },
  {
    id: 9,
    name: "Smart TV DLED 43 Full HD Toshiba 43v35ms VIDAA 2HDMI 2USB WI-FI - TB053E",
    price: 1899.00,
    oldPrice: 2299.00,
    discount: 17,
    sales: 180,
    rating: 4.8,
    screenSize: '43',
    os: 'VIDAA',
    imageUrl: "https://i.postimg.cc/9MZ6Yy0g/image.png",
    affiliateUrl: "https://s.shopee.com.br/4LCjOfhnS4",
  },
];
